### ISSUE TITLE
Data selection form field issue and no API requests works. Constantly throw 400 bad requests

### ISSUE THREAD

**Issue by Rolence** [openMF/web-app#1392]
All forms collecting date throws this error. 
main.js:1 ERROR SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at t.get [as language] (main.js:1:1682129)
    at t.submit (main.js:1:4900774)
    at main.js:1:4901957
    at ga (main.js:1:903921)
    at r (main.js:1:904083)
    at e.o [as _next] (main.js:1:940244)
    at e.__tryOrUnsub (main.js:1:980751)
    at e.next (main.js:1:979896)
    at e._next (main.js:1:978972)

And the data field automatically clears and reset to empty field

**Comment by bharathcgowda** [comment]
Hi @Rolence  could you please add more information to the ticket, any screenshots and steps to reproduce will be helpful

**Comment by ramvr1256** [comment]
Working correctly. It was an issue of the previous version of fineract backend

**Comment by ramvr1256** [comment]
Kindly check on the webapp.ps.mifos.io instead of openmf.mifos.io. That is using a previous version of backend
