### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by HarimbolaSantatra** [openMF/web-app#2185]
## Description
Provide a brief overview of the enhancement or issue.

## Steps to Reproduce
```
git clone --depth=1 https://github.com/openMF/web-app
cd web-app
npm install
npm run build:prod
```

## Expected Behaviour
Artifact is build.

## Actual Behaviour
Output:
```
> mifosx-web-app@0.10.0 postinstall /home/santatra/cb/web-app
> node version.js && ngcc

Wrote version info 2b730bb to web-app/src/environments/.env.ts
/home/santatra/cb/web-app/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:3
      import {createRequire as __cjsCompatRequire} from 'module';
             ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mifosx-web-app@0.10.0 postinstall: `node version.js && ngcc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mifosx-web-app@0.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
## Settings
- Mifos X version: current master branch
- Browser used: Not relevant

**Comment by R-Kri** [comment]
This error is due to an outdated Node.js version, which doesn't support ES module syntax used by Angular's Ivy compiler (ngcc). To fix this issue, the project requires Node.js 14.x or higher.

Solution:
1. Upgrade Node.js to version 14 or above 
2. Reinstall Dependencies.
