### ISSUE TITLE
Not able to launch the mifosx in my local machine

### ISSUE THREAD

**Issue by subsnrao** [openMF/web-app#734]
Followed the instructions in the https://github.com/openMF/web-app and tried to launch the application locally, found the following error 
$ npm install
npm WARN deprecated istanbul@0.3.22: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated validate-commit-msg@2.14.0: Check out CommitLint which provides the same functionality with a more user-focused experience.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated request@2.79.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated npmconf@2.1.3: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated @semantic-release/condition-travis@4.1.4: Use semantic-release@12.0.0 instead
npm WARN deprecated @semantic-release/last-release-npm@1.2.1: Use @semantic-release/npm instead
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated conventional-changelog@0.0.17: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> execSync@1.0.2 install E:\web-app\node_modules\app-root-path\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.

> ghooks@1.3.2 install E:\web-app\node_modules\app-root-path\node_modules\ghooks
> node ./bin/module-install

npm notice created a lockfile as package-lock.json. You should commit this file.
added 508 packages from 623 contributors and audited 1232 packages in 50.423s

1 package is looking for funding
  run `npm fund` for details

found 83 vulnerabilities (32 low, 13 moderate, 36 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

Hp@DESKTOP-1ESNBTQ MINGW64 /e/web-app/node_modules/app-root-path (master)
$ ng serve
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber.project (E:\web-app\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\workspace\workspace.js:215:42)
    at MergeMapSubscriber._tryNext (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MapSubscriber._next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\map.js:55:26)
    at MapSubscriber.Subscriber.next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:86:26)
    at InnerSubscriber._next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:65:54)
    at SwitchMapSubscriber._next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:86:26)
    at InnerSubscriber._next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:67:18)
    at E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult (E:\web-app\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)

Hp@DESKTOP-1ESNBTQ MINGW64 /e/web-app/node_modules/app-root-path (master)
$

Regards,
Subbu

**Comment by karantakalkar** [comment]
Hi @subsnrao can you try this workaround
 https://stackoverflow.com/questions/56393158/errors-data-path-buildersapp-shell-should-have-required-property-class

**Comment by karantakalkar** [comment]
User specific issue.

**Comment by abhaychawla** [comment]
@subsnrao Please do not open issues for general support questions as we want to keep GitHub issues for bug reports and feature requests. If you have got any questions, please email to our mailing list. You can also join our gitter channel. Please refer the Contribution Guidelines.

**Comment by subsnrao** [comment]
Hi Karan Takalkar,
Nothing worked out for me. I am not finding the base database folder in the
download. In
https://cwiki.apache.org/confluence/display/FINERACT/Fineract-platform+Installation+on+Windows
. *mifospltaform-tenants-first-time-install.sql.*
 Please suggest.

Regards,
Subbu
